# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [12]:
# Import torch
import torch
print(torch.backends.mps.is_available())

# Create random tensor
tensor_1 = torch.rand(size = [7, 7])
print(tensor_1)

True
tensor([[0.9777, 0.0123, 0.3152, 0.5784, 0.2362, 0.4315, 0.2421],
        [0.5370, 0.9208, 0.4689, 0.6157, 0.2583, 0.0829, 0.6384],
        [0.4944, 0.1504, 0.3099, 0.0732, 0.1647, 0.9291, 0.9636],
        [0.1722, 0.9089, 0.9556, 0.1695, 0.1532, 0.4383, 0.7965],
        [0.4528, 0.0735, 0.7448, 0.7609, 0.5779, 0.6684, 0.8472],
        [0.6803, 0.9706, 0.8304, 0.7367, 0.0358, 0.6974, 0.0403],
        [0.8898, 0.3343, 0.3029, 0.3342, 0.5290, 0.2472, 0.7788]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
tensor_2 = torch.rand(size = [1, 7])

# Perform matrix multiplication 
tensor_3 = torch.matmul(tensor_1, tensor_2.reshape(7, 1))
print(tensor_3)

tensor([[0.5142],
        [1.5595],
        [1.4666],
        [1.1538],
        [2.0078],
        [1.7487],
        [1.5248]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [14]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
tensor_1 = torch.rand(size = [7, 7])
tensor_2 = torch.rand(size = [1, 7])

# Matrix multiply tensors
tensor_3 = torch.matmul(tensor_1, tensor_2.reshape(7, 1))
print(tensor_3)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [31]:
# Set random seed
torch.manual_seed(1234)


# Check for access to GPU
print(torch.backends.mps.is_available())

# Create two random tensors on GPU
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

tensor_1 = torch.rand(size=(2, 3)).to(device)
tensor_2 = torch.rand(size=(2, 3)).to(device)

print(tensor_2, tensor_2.device)

True
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='mps:0') mps:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [32]:
# Perform matmul on tensor_A and tensor_B
tensor_mul_gpu = torch.matmul(tensor_1, tensor_2.view(3, 2))
tensor_mul_gpu, tensor_mul_gpu.device

(tensor([[0.4759, 0.2931],
         [0.6074, 0.5855]], device='mps:0'),
 device(type='mps', index=0))

### 8. Find the maximum and minimum values of the output of 7.

In [33]:
# Find max
print(tensor_mul_gpu.max())

# Find min
print(tensor_mul_gpu.min())

tensor(0.6074, device='mps:0')
tensor(0.2931, device='mps:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [34]:
# Find arg max
print(tensor_mul_gpu.argmax())

# Find arg min
print(tensor_mul_gpu.argmin())

tensor(2, device='mps:0')
tensor(1, device='mps:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [37]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_1 = torch.rand(size = (1, 1, 1, 10))

# Remove single dimensions
tensor_1 = tensor_1.reshape(10)

# Print out tensors and their shapes
print(tensor_1, tensor_1.shape)

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
