
# Implement Common Activation Functions  

## Task: Implement Common Activation Functions  
Your task is to implement commonly used activation functions in deep learning. Activation functions introduce non-linearity to neural networks, allowing them to model complex patterns.  

You need to write a function `activation(x, func)` that applies the specified activation function to an input array. The function should accept:  

- `x`: A NumPy array representing the input values.  
- `func`: A string specifying the activation function to use. It can be one of:  
  - `"relu"` (Rectified Linear Unit)  
  - `"sigmoid"`  
  - `"tanh"`  
  - `"softmax"`  

Your function should return a NumPy array with the transformed values. If an invalid activation function is provided, return `None`.  

## Example  
### **Input:**  
```python
import numpy as np

x = np.array([-1.0, 0.0, 1.0, 2.0])

print(activation(x, "relu"))
print(activation(x, "sigmoid"))
print(activation(x, "tanh"))
print(activation(x, "softmax"))
```
### **Output:**  
```python
# [0. 0. 1. 2.]  # ReLU
# [0.2689 0.5 0.7311 0.8808]  # Sigmoid
# [-0.7616 0.0 0.7616 0.9640]  # Tanh
# [0.0321 0.0871 0.2369 0.6438]  # Softmax
```

## **Explanation:**  
- **ReLU** replaces negative values with zero (`max(0, x)`).  
- **Sigmoid** squashes values to the range (0,1).  
- **Tanh** squashes values to the range (-1,1).  
- **Softmax** converts values into probabilities that sum to 1.  
```

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x)

def softmax(x):
    # e ** x / sum(e ** x)
    prob_sum = np.sum(np.exp(x))
    return np.exp(x) / prob_sum

def Relu(x):
    return np.where(x < 0, 0, x)

def Tanh(x):
    # 2 / (1 + e ** -2x)
    return 2 /  (1 + np.exp(2 * x)

def activation(x, activation_function):
    if function == 'sigmoid':
        pass
        